/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import javax.swing.JOptionPane;

/**
 *
 * @author Vinesh Sundar Parmar
 */
public class resultcomm extends javax.swing.JFrame {

    /**
     * Creates new form resultcomm
     */
    public resultcomm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton4.setText("Publish");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("SESSION");

        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ENGLISH",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"HINDI",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"MATHS",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"ACCOUNTS",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"B.STUDIES",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"ECO.",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"I.P.",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)}
            },
            new String [] {
                "SUBJECT", "UNIT TEST I", "UNIT TEST II", "UNIT TEST III", "HALF YEARLY EXAM", "FINAL EXAM", "PRACTICAL H.Y.E.", "PRACTICAL S.E.E."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable3FocusLost(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable3KeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton5.setText("Check Data ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Next");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        jTabbedPane2.addTab("tab1", jPanel1);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("ASSIGNMENT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ACCOUNTS",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"ENGLISH",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"HINDI",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"MATHS",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"B.STUDIES",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"ECO.",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"I.P.",  new Integer(0),  new Integer(0),  new Integer(0)}
            },
            new String [] {
                "SUBJECT", "I TERM", "II TERM", "III TERM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Next Tab");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("CHECK DATA");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab6", jPanel6);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ACCOUNTS",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"ENGLISH",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"HINDI",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"MATHS",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"B.STUDIES",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"ECO.",  new Integer(0),  new Integer(0),  new Integer(0)},
                {"IP",  new Integer(0),  new Integer(0),  new Integer(0)}
            },
            new String [] {
                "SUBJECT", "I TERM", "II TERM", "III TERM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable2FocusLost(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("PROJECT");

        jButton3.setText("ENTER DATA ");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("CHECK DATA");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab7", jPanel7);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setText("ROLLNO");

        jTextField5.setText("2014-15");
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jLabel3.setText("ADMNO");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel2.setText("NAME");

        jTextField4.setText("11");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel4.setText("CLASS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            School.name=jTextField2.getText();
            School.roll=jTextField1.getText();
            School.admno=jTextField3.getText();
            School.cls=jTextField4.getText();
            School.session=jTextField5.getText();

            School.Rengut=Math.round(School.engut/8.0);
            School.Raccut=Math.round(School.accut/8.0);
            School.Rbsut=Math.round(School.bsut/8.0);
            School.Rhinut=Math.round(School.hinut/8.0);
            School.Rmthsut=Math.round(School.mthsut/8.0);
            School.Recout=Math.round(School.ecout/8.0);
            School.Riput=Math.round(School.iput/8.0);

            

            School.Renghy=Math.round(School.enghy/4.0);
            School.Racchy=Math.round(School.acchy/4.0);
            School.Rbshy=Math.round(School.bshy/4.0);
            School.Rhinhy=Math.round(School.hinhy/4.0);
            School.Rmthshy=Math.round(School.mthshy/4.0);
            School.Recohy=Math.round(School.ecohy/4.0);
            School.Riphy=Math.round(School.iphy/3.5);

            

            School.Rengse=Math.round(School.engse/2.0);
            School.Raccse=Math.round(School.accse/2.0);
            School.Rbsse=Math.round(School.bsse/2.0);
            School.Rhinse=Math.round(School.hinse/2.0);
            School.Rmthsse=Math.round(School.mthsse/2.0);
            School.Recose=Math.round(School.ecose/2.0);
            School.Ripse=Math.round(School.ipse/2.0);

            

            School.RA_mths=Math.round(School.A_mths/20.0);
            School.RA_acc=Math.round(School.A_acc/20.0);
            School.RA_bs=Math.round(School.A_bs/20.0);
            School.RA_eng=Math.round(School.A_eng/20.0);
            School.RA_ip=Math.round(School.A_ip/20.0);
            School.RA_eco=Math.round(School.A_eco/20.0);
            School.RA_hin=Math.round(School.A_hin/20.0);

            
            School.RP_mths=Math.round(School.P_mths/20.0);
            School.RP_acc=Math.round(School.P_acc/20.0);
            School.RP_bs=Math.round(School.P_bs/20.0);
            School.RP_eng=Math.round(School.P_eng/20.0);
            School.RP_ip=Math.round(School.P_ip/20.0);
            School.RP_eco=Math.round(School.P_eco/20.0);
            School.RP_hin=Math.round(School.P_hin/20.0);

            
            School.Rhyprac_ip=Math.round(School.hyprac_ip/6.0);
            
            School.Rseprac_ip=Math.round(School.seprac_ip/2.0);
            
            School.Teng=School.RP_eng+School.RA_eng+School.Rengut+School.Renghy+School.Rengse;
            School.Thin=School.RP_hin+School.RA_hin+School.Rhinut+School.Rhinhy+School.Rhinse;
            School.Tmths=School.RP_mths+School.RA_mths+School.Rmthsut+School.Rmthshy+School.Rmthsse;

            School.Tacc=School.RP_acc+School.RA_acc+School.Raccut+School.Racchy+School.Raccse;
            School.Tbs=School.RP_bs+School.RA_bs+School.Rbsut+School.Rbshy+School.Rbsse;
            School.Teco=School.RP_eco+School.RA_eco+School.Recout+School.Recohy+School.Recose;
            School.Tip=School.RP_ip+School.RA_ip+School.Riput+School.Riphy+School.Ripse+School.Rhyprac_ip+School.Rseprac_ip;

            new reportcardcomm().setVisible(true);
            dispose();
        }catch(Exception e)
        {}

        //jTabbedPane2.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyTyped
        if(!(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'))
        {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTable3KeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try
{
    jButton1.nextFocus();
    boolean b=((int)jTable3.getValueAt(0, 1)>40||(int)jTable3.getValueAt(0, 2)>40||(int)jTable3.getValueAt(0, 3)>40||(int)jTable3.getValueAt(1, 1)>40||(int)jTable3.getValueAt(1, 2)>40||(int)jTable3.getValueAt(1, 3)>40||(int)jTable3.getValueAt(2, 1)>40||(int)jTable3.getValueAt(2, 2)>40||(int)jTable3.getValueAt(2, 3)>40||(int)jTable3.getValueAt(3, 1)>40||(int)jTable3.getValueAt(3, 2)>40);//||jTable3.getValueAt(0, 2)>40||
    boolean d=((int)jTable3.getValueAt(0, 4)>100||(int)jTable3.getValueAt(0, 5)>100||(int)jTable3.getValueAt(1, 4)>100||(int)jTable3.getValueAt(1, 5)>100||(int)jTable3.getValueAt(2, 4)>100||(int)jTable3.getValueAt(2, 5)>100||(int)jTable3.getValueAt(3, 4)>100||(int)jTable3.getValueAt(3, 5)>100||(int)jTable3.getValueAt(4, 4)>100||(int)jTable3.getValueAt(4, 5)>100||(int)jTable3.getValueAt(5, 4)>100);//||jTable3.getValueAt(0, 2)>40||
    boolean e=((int)jTable3.getValueAt(5, 5)>100||(int)jTable3.getValueAt(6, 4)>70||(int)jTable3.getValueAt(6, 5)>70);//||(int)jTable3.getValueAt(1, 5)>100||(int)jTable3.getValueAt(2, 4)>100);
    boolean c=((int)jTable3.getValueAt(3, 3)>40||(int)jTable3.getValueAt(4, 1)>40||(int)jTable3.getValueAt(4, 2)>40||(int)jTable3.getValueAt(4, 3)>40||(int)jTable3.getValueAt(5, 1)>40||(int)jTable3.getValueAt(5, 2)>40||(int)jTable3.getValueAt(5,3)>40||(int)jTable3.getValueAt(6, 1)>40||(int)jTable3.getValueAt(6, 2)>40||(int)jTable3.getValueAt(6, 3)>40);//||(int)jTable3.getValueAt(3, 2)>40);
    boolean f=((int)jTable3.getValueAt(3, 6)>0||(int)jTable3.getValueAt(3, 7)>0||(int)jTable3.getValueAt(4, 6)>0);
    boolean g=((int)jTable3.getValueAt(4, 7)>0||(int)jTable3.getValueAt(5, 7)>0||(int)jTable3.getValueAt(5, 6)>0);
    boolean h=((int)jTable3.getValueAt(6, 6)>30||(int)jTable3.getValueAt(6, 7)>30||(int)jTable3.getValueAt(4, 6)>0);
    
    for(int r=0;r<=6;r++)
    {
        for(int col=1;col<=7;col++)
        {
            if(jTable3.getValueAt(r, col).equals(null))
            {
                jTable3.setValueAt(0,r, col);
            }
        }
    
    }
    
    
    if(b==true || c==true||d==true || e==true||f==true || g==true||h==true)
    {
    JOptionPane.showMessageDialog(rootPane, "MARKS OVER THE LIMIT.....");
    }
    else
    {
        jButton1.setEnabled(true);
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            jButton6.setEnabled(true);

            School.engut=(int)jTable3.getValueAt(0, 1)+(int)jTable3.getValueAt(0, 2)+(int)jTable3.getValueAt(0, 3);

            School.hinut=(int)jTable3.getValueAt(1, 1)+(int)jTable3.getValueAt(1, 2)+(int)jTable3.getValueAt(1, 3);

            School.mthsut=(int)jTable3.getValueAt(2, 1)+(int)jTable3.getValueAt(2, 2)+(int)jTable3.getValueAt(2, 3);
            School.accut=(int)jTable3.getValueAt(3, 1)+(int)jTable3.getValueAt(3, 2)+(int)jTable3.getValueAt(3, 3);

            School.bsut=(int)jTable3.getValueAt(4, 1)+(int)jTable3.getValueAt(4, 2)+(int)jTable3.getValueAt(4, 3);

            School.ecout=(int)jTable3.getValueAt(5, 1)+(int)jTable3.getValueAt(5, 2)+(int)jTable3.getValueAt(5, 3);

            School.iput=(int)jTable3.getValueAt(6, 1)+(int)jTable3.getValueAt(6, 2)+(int)jTable3.getValueAt(6, 3);

            School.enghy=(int)jTable3.getValueAt(0, 4);
            School.hinhy=(int)jTable3.getValueAt(1, 4);
            School.mthshy=(int)jTable3.getValueAt(2,4);
            School.acchy=(int)jTable3.getValueAt(3, 4);
            School.bshy=(int)jTable3.getValueAt(4, 4);
            School.ecohy=(int)jTable3.getValueAt(5, 4);
            School.iphy=(int)jTable3.getValueAt(6, 4);

            School.engse=(int)jTable3.getValueAt(0, 5);
            School.hinse=(int)jTable3.getValueAt(1, 5);
            School.mthsse=(int)jTable3.getValueAt(2,5);
            School.accse=(int)jTable3.getValueAt(3, 5);
            School.bsse=(int)jTable3.getValueAt(4, 5);
            School.ecose=(int)jTable3.getValueAt(5, 5);
            School.ipse=(int)jTable3.getValueAt(6, 5);

            
            School.hyprac_ip=(int)jTable3.getValueAt(6, 6);           
            School.seprac_ip=(int)jTable3.getValueAt(6, 7);

            jTabbedPane2.setSelectedIndex(1);

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        if(!(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{School.A_eng=(int)jTable1.getValueAt(1, 1)+(int)jTable1.getValueAt(1, 2)+(int)jTable1.getValueAt(1, 3);
            School.A_hin=(int)jTable1.getValueAt(2, 1)+(int)jTable1.getValueAt(2, 2)+(int)jTable1.getValueAt(2, 3);
            School.A_mths=(int)jTable1.getValueAt(3, 1)+(int)jTable1.getValueAt(3, 2)+(int)jTable1.getValueAt(3, 3);
            School.A_acc=(int)jTable1.getValueAt(0, 1)+(int)jTable1.getValueAt(0, 2)+(int)jTable1.getValueAt(0, 3);
            School.A_bs=(int)jTable1.getValueAt(4, 1)+(int)jTable1.getValueAt(4, 2)+(int)jTable1.getValueAt(4, 3);
            School.A_ip=(int)jTable1.getValueAt(6, 1)+(int)jTable1.getValueAt(6, 2)+(int)jTable1.getValueAt(6, 3);
            School.A_eco=(int)jTable1.getValueAt(5, 1)+(int)jTable1.getValueAt(5, 2)+(int)jTable1.getValueAt(5, 3);
            jTabbedPane2.setSelectedIndex(2);
            jButton7.setEnabled(true);
        } catch(Exception e)
        {}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyTyped
        if(!(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{School.P_eng=(int)jTable2.getValueAt(1, 1)+(int)jTable2.getValueAt(1, 2)+(int)jTable2.getValueAt(1, 3);
            School.P_hin=(int)jTable2.getValueAt(2, 1)+(int)jTable2.getValueAt(2, 2)+(int)jTable2.getValueAt(2, 3);
            School.P_mths=(int)jTable2.getValueAt(3, 1)+(int)jTable2.getValueAt(3, 2)+(int)jTable2.getValueAt(3, 3);
            School.P_acc=(int)jTable2.getValueAt(0, 1)+(int)jTable2.getValueAt(0, 2)+(int)jTable2.getValueAt(0, 3);
            School.P_bs=(int)jTable2.getValueAt(4, 1)+(int)jTable2.getValueAt(4, 2)+(int)jTable2.getValueAt(4, 3);
            School.P_ip=(int)jTable2.getValueAt(6, 1)+(int)jTable2.getValueAt(6, 2)+(int)jTable2.getValueAt(6, 3);
            School.P_eco=(int)jTable2.getValueAt(5, 1)+(int)jTable2.getValueAt(5, 2)+(int)jTable2.getValueAt(5, 3);
            jButton4.setEnabled(true);
        }catch(Exception e)
        {}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if(!(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        String session=jTextField5.getText();
        int l=session.length();

        if(!(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'&&evt.getKeyChar()=='-'))
        {
            evt.consume();
        }
        else
        {      for(int n=0;n<l;n++)
            {
                if(evt.getKeyChar()=='-'&&session.charAt(n)=='-')
                {
                    evt.consume();
                }
                if(evt.getKeyChar()=='-' &&n==0 )
                {
                    evt.consume();
                }

            }

            // here i have to apply a condition check...if(sessio)

        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        if(!(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'))
        {
            evt.consume();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        if(!(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTable3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable3FocusLost
 if(School.sub1.equalsIgnoreCase("hindi"))
{
for(int col=1;col<=7;col++)
{
jTable3.setValueAt(0,6, col);
}
}
else
{
for(int col=1;col<=7;col++)
{
jTable3.setValueAt(0,1, col);
}
}
if(School.sub2.equalsIgnoreCase("eco"))
{
for(int col=1;col<=7;col++)
{
jTable3.setValueAt(0,2, col);
}
}
else
{
for(int col=1;col<=7;col++)
{
jTable3.setValueAt(0,5, col);
}
}       // TODO add your handling code here:
    }//GEN-LAST:event_jTable3FocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
{
    School.sub1=JOptionPane.showInputDialog("HINDI OR IP????");
    while(!(School.sub1.equalsIgnoreCase("hindi")||School.sub1.equalsIgnoreCase("ip")))
    {
        School.sub1=JOptionPane.showInputDialog("HINDI OR IP????");
    }

    School.sub2=JOptionPane.showInputDialog("ECO OR MATHS????");
    while(!(School.sub2.equalsIgnoreCase("eco")||School.sub2.equalsIgnoreCase("maths")))
    {
        School.sub2=JOptionPane.showInputDialog("ECO OR MATHS????");
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
try
{
    int col;
    if(School.sub1.equalsIgnoreCase("hindi"))
    {
        for(col=1;col<=3;col++)
        {
            jTable1.setValueAt(0,6, col);
        }
    }
    else
    {
        for(col=1;col<=3;col++)
        {
            jTable1.setValueAt(0,2, col);
        }
    }
    
    if(School.sub2.equalsIgnoreCase("eco"))
    {
        for(col=1;col<=3;col++)
        {
            jTable1.setValueAt(0,3, col);
        }
    }
    else
    {
        for(col=1;col<=3;col++)
        {
            jTable1.setValueAt(0,5, col);
        }
    }
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusLost
try
{
    int col;
    if(School.sub1.equalsIgnoreCase("hindi"))
    {
        for(col=1;col<=3;col++)
        {
            jTable2.setValueAt(0,6, col);
        }
    }
    else
    {
        for(col=1;col<=3;col++)
        {
            jTable2.setValueAt(0,2, col);
        }
    }
    
    if(School.sub2.equalsIgnoreCase("eco"))
    {
        for(col=1;col<=3;col++)
        {
            jTable2.setValueAt(0,3, col);
        }
    }
    else
    {
        for(col=1;col<=3;col++)
        {
            jTable2.setValueAt(0,5, col);
        }
    }
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_jTable2FocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try{
        jButton2.nextFocus();
        boolean b=((int)jTable1.getValueAt(0, 1)>30||(int)jTable1.getValueAt(0, 2)>30||(int)jTable1.getValueAt(0, 3)>40||(int)jTable1.getValueAt(1, 1)>30||(int)jTable1.getValueAt(1, 2)>30||(int)jTable1.getValueAt(1, 3)>40||(int)jTable1.getValueAt(2, 1)>30||(int)jTable1.getValueAt(2, 2)>30||(int)jTable1.getValueAt(2, 3)>40||(int)jTable1.getValueAt(3, 1)>30||(int)jTable1.getValueAt(3, 2)>30);//||jTable3.getValueAt(0, 2)>40||
            // TODO add your handling code here:
boolean c=((int)jTable1.getValueAt(3, 3)>40||(int)jTable1.getValueAt(4, 1)>30||(int)jTable1.getValueAt(4, 2)>30||(int)jTable1.getValueAt(4, 3)>40||(int)jTable1.getValueAt(5, 1)>30||(int)jTable1.getValueAt(5, 2)>30||(int)jTable1.getValueAt(5, 3)>40||(int)jTable1.getValueAt(6, 1)>30||(int)jTable1.getValueAt(6, 2)>30||(int)jTable1.getValueAt(6, 3)>40);//||(int)jTable1.getValueAt(3, 2)>30);//||jTable3.getValueAt(0, 2)>40||
            // TODO add your handling code here:
if(b==true||c==true)
{
    JOptionPane.showMessageDialog(rootPane, "MARKS OVER THE LIMIT.....");
}
else
{
    jButton2.setEnabled(true);
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try{
    
    jButton3.nextFocus();
    
    boolean b=((int)jTable1.getValueAt(0, 1)>30||(int)jTable1.getValueAt(0, 2)>30||(int)jTable1.getValueAt(0, 3)>40||(int)jTable1.getValueAt(1, 1)>30||(int)jTable1.getValueAt(1, 2)>30||(int)jTable1.getValueAt(1, 3)>40||(int)jTable1.getValueAt(2, 1)>30||(int)jTable1.getValueAt(2, 2)>30||(int)jTable1.getValueAt(2, 3)>40||(int)jTable1.getValueAt(3, 1)>30||(int)jTable1.getValueAt(3, 2)>30);//||jTable3.getValueAt(0, 2)>40||
            // TODO add your handling code here:
boolean c=((int)jTable1.getValueAt(3, 3)>40||(int)jTable1.getValueAt(4, 1)>30||(int)jTable1.getValueAt(4, 2)>30||(int)jTable1.getValueAt(4, 3)>40||(int)jTable1.getValueAt(5, 1)>30||(int)jTable1.getValueAt(5, 2)>30||(int)jTable1.getValueAt(5, 3)>40||(int)jTable1.getValueAt(6, 1)>30||(int)jTable1.getValueAt(6, 2)>30||(int)jTable1.getValueAt(6, 3)>40);//||(int)jTable1.getValueAt(3, 2)>30);//||jTable3.getValueAt(0, 2)>40||
            // TODO add your handling code here:
if(b==true||c==true)
{
    JOptionPane.showMessageDialog(rootPane, "MARKS OVER THE LIMIT.....");
}
else
{
    jButton3.setEnabled(true);
}   
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultcomm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultcomm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultcomm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultcomm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultcomm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
